# <u>**Part 2**

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(data={'weight': [75., 78.5, 85., 91., 84.5, 83., 68.]})
df

   weight
0    75.0
1    78.5
2    85.0
3    91.0
4    84.5
5    83.0
6    68.0

In [3]:
df['weight_cut'] = pd.cut(df['weight'], bins=(60, 75, 80, 95),
                          labels=['light', 'normal', 'heavy'])
df

   weight weight_cut
0    75.0      light
1    78.5     normal
2    85.0      heavy
3    91.0      heavy
4    84.5      heavy
5    83.0      heavy
6    68.0      light

### **Exercise 11**

Convert weight_cut categorical column into dummy variable

In [4]:
pd.get_dummies(df)

   weight  weight_cut_light  weight_cut_normal  weight_cut_heavy
0    75.0                 1                  0                 0
1    78.5                 0                  1                 0
2    85.0                 0                  0                 1
3    91.0                 0                  0                 1
4    84.5                 0                  0                 1
5    83.0                 0                  0                 1
6    68.0                 1                  0                 0

### **Exercise 12**

The following dictionary is given

* 
data_dict = {
    'currency': [['PLN', 'USD'], ['EUR', 'USD', 'PLN', 'CAD'], ['GBP'], ['JPY', 'CZK', 'HUF'], []]
}

Convert the dictionary to a dataframe. Assign a new column 'number' that takes the number of items in the currency column.

In [5]:
data_dict = {
    'currency': [['PLN', 'USD'], ['EUR', 'USD', 'PLN', 'CAD'], ['GBP'], ['JPY', 'CZK', 'HUF'], []]
}

df = pd.DataFrame(data_dict)
df

               currency
0            [PLN, USD]
1  [EUR, USD, PLN, CAD]
2                 [GBP]
3       [JPY, CZK, HUF]
4                    []

In [6]:
df['number'] = df['currency'].apply(len)
df

               currency  number
0            [PLN, USD]       2
1  [EUR, USD, PLN, CAD]       4
2                 [GBP]       1
3       [JPY, CZK, HUF]       3
4                    []       0

### **Exercise 13**

Assign a new column 'PLN_flag' which stores 1 when the currency 'PLN' is in the currency column, otherwise 0

In [7]:
df['PLN_flag'] = df['currency'].apply(lambda col: 1 if 'PLN' in col else 0)
df

               currency  number  PLN_flag
0            [PLN, USD]       2         1
1  [EUR, USD, PLN, CAD]       4         1
2                 [GBP]       1         0
3       [JPY, CZK, HUF]       3         0
4                    []       0         0

### **Exercise 14**

Create the following dataframe.

<pre>
     hashtags

0  #good#vibes <br>
1  #hot#summer#holiday <br>
2  #street#food<br>
3  #workout<br>

</pre>

Split hashtags by the '#' sign using pd.Series.str.split() with argument expand = True. You will get four columns. For example, for the second row:

* #hot#summer#holiday

returns the following list

* [' ', 'hot', 'summer', 'holiday']

Remove the first column from the result (the first column contains only empty strings ''). Then assign the names of the remaining columns as follows:

* hashtag1
* hashtag2
* hashtag3

In [8]:
data_dict = {'hashtags': ['#good#vibes', 
                          '#hot#summer#holiday', 
                          '#street#food', 
                          '#workout']}

df = pd.DataFrame(data_dict)
df

              hashtags
0          #good#vibes
1  #hot#summer#holiday
2         #street#food
3             #workout

In [9]:
df = df['hashtags'].str.split('#', expand=True)
df

  0        1       2        3
0       good   vibes     None
1        hot  summer  holiday
2     street    food     None
3    workout    None     None

In [10]:
df = df.drop(columns=[0])
df

         1       2        3
0     good   vibes     None
1      hot  summer  holiday
2   street    food     None
3  workout    None     None

In [11]:
df.columns = ['hashtag1', 'hashtag2', 'hashtag3']
df

  hashtag1 hashtag2 hashtag3
0     good    vibes     None
1      hot   summer  holiday
2   street     food     None
3  workout     None     None

### **Exercise 15**

Create a new column 'missing' and assign the number of missing hashtags for each row as shown below. 

* row one -> 1
* row two -> 0
* row three -> 1
* row four -> 2

In [12]:
df['missing'] = df.isnull().sum(axis=1)
df

  hashtag1 hashtag2 hashtag3  missing
0     good    vibes     None        1
1      hot   summer  holiday        0
2   street     food     None        1
3  workout     None     None        2

### **Exercise 16**

Convert the following dictionary 

data_dict = {
    'investments': [
        '100_000_000', 
        '100_000', 
        '30_000_000', 
        '100_500_000'
    ]
}

into a dataframe. Then convert the *investments* column to int type.

In [13]:
data_dict = {'investments': ['100_000_000',
                             '100_000',
                             '30_000_000', 
                             '100_500_000']}

In [14]:
df = pd.DataFrame(data_dict)
df

   investments
0  100_000_000
1      100_000
2   30_000_000
3  100_500_000

In [15]:
df['investments'] = df['investments'].str.replace('_', '').astype(int)
df

   investments
0    100000000
1       100000
2     30000000
3    100500000

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   investments  4 non-null      int64
dtypes: int64(1)
memory usage: 160.0 bytes

### **Exercise 17**

Load the *IRIS* dataset into the data variable using the scikit-learn package and the load_iris() function.

Then print all the keys of the data variable

In [20]:
from sklearn.datasets import load_iris

In [21]:
data_raw = load_iris()
data_raw.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

### **Exercise 18**

Print all feature variable names and all class names from the IRIS data set

In [22]:
print(data_raw['feature_names'])
print(data_raw['target_names'])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']

## **Exercise 19**

Assign the 'data' keyto the data variable. Then assign 'target' key to the target variable. Then print the shape of these arrays

In [23]:
data = data_raw['data']
target = data_raw['target']
print(data.shape)
print(target.shape)

(150, 4)
(150,)

### **Exercise 20**

Using the scikit-learn package and the train_test_split() function, split the data into the training set (data_train, target_train) and the test set (data_test, target_test). Set the test size to 30% of the samples.

As an answer, print the shapes of the following arrays:

* data_train
* target_train
* data_test
* target_test

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
data_train, data_test, target_train, target_test = train_test_split(data, target, test_size=0.3)

In [27]:
print('data_train shape: ', data_train.shape)
print('data_test shape: ', data_test.shape)
print('target_train shape: ', target_train.shape)
print('target_test shape: ', target_test.shape)

data_train shape:  (105, 4)
data_test shape:  (45, 4)
target_train shape:  (105,)
target_test shape:  (45,)